// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertLogBatch implements pgx.CopyFromSource.
type iteratorForInsertLogBatch struct {
	rows                 []InsertLogBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLogBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLogBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Level,
		r.rows[0].Message,
		r.rows[0].Timestamp,
		r.rows[0].Caller,
		r.rows[0].StackTrace,
		r.rows[0].Fields,
	}, nil
}

func (r iteratorForInsertLogBatch) Err() error {
	return nil
}

func (q *Queries) InsertLogBatch(ctx context.Context, arg []InsertLogBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"application_logs"}, []string{"level", "message", "timestamp", "caller", "stack_trace", "fields"}, &iteratorForInsertLogBatch{rows: arg})
}
