// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID               int32            `json:"id"`
	UserID           int32            `json:"user_id"`
	StravaActivityID int64            `json:"strava_activity_id"`
	Name             pgtype.Text      `json:"name"`
	Type             pgtype.Text      `json:"type"`
	Distance         pgtype.Float8    `json:"distance"`
	MovingTime       pgtype.Int4      `json:"moving_time"`
	ElapsedTime      pgtype.Int4      `json:"elapsed_time"`
	StartDate        pgtype.Timestamp `json:"start_date"`
	StartDateLocal   pgtype.Timestamp `json:"start_date_local"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type ApplicationLog struct {
	ID         int64            `json:"id"`
	Level      string           `json:"level"`
	Message    string           `json:"message"`
	Timestamp  pgtype.Timestamp `json:"timestamp"`
	Caller     pgtype.Text      `json:"caller"`
	StackTrace pgtype.Text      `json:"stack_trace"`
	Fields     []byte           `json:"fields"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID             int32            `json:"id"`
	StravaUserID   int64            `json:"strava_user_id"`
	Username       pgtype.Text      `json:"username"`
	AccessToken    string           `json:"access_token"`
	RefreshToken   string           `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamp `json:"token_expires_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
