// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupOldLogs(ctx context.Context, timestamp pgtype.Timestamp) error
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActivity(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetActivitiesByDateRange(ctx context.Context, arg GetActivitiesByDateRangeParams) ([]Activity, error)
	GetActivity(ctx context.Context, id int32) (Activity, error)
	GetActivityByStravaID(ctx context.Context, stravaActivityID int64) (Activity, error)
	GetActivityStats(ctx context.Context, userID int32) (GetActivityStatsRow, error)
	GetCalendarData(ctx context.Context, arg GetCalendarDataParams) ([]GetCalendarDataRow, error)
	GetLogsByLevel(ctx context.Context, arg GetLogsByLevelParams) ([]ApplicationLog, error)
	GetLogsByUserID(ctx context.Context, arg GetLogsByUserIDParams) ([]ApplicationLog, error)
	GetRecentActivities(ctx context.Context, arg GetRecentActivitiesParams) ([]Activity, error)
	GetRecentLogs(ctx context.Context, arg GetRecentLogsParams) ([]ApplicationLog, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByStravaID(ctx context.Context, stravaUserID int64) (User, error)
	InsertLogBatch(ctx context.Context, arg []InsertLogBatchParams) (int64, error)
	ListActivitiesByUser(ctx context.Context, arg ListActivitiesByUserParams) ([]Activity, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) (User, error)
	UpsertActivity(ctx context.Context, arg UpsertActivityParams) (Activity, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
