// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    strava_user_id,
    username,
    access_token,
    refresh_token,
    token_expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, strava_user_id, username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateUserParams struct {
	StravaUserID   int64            `json:"strava_user_id"`
	Username       pgtype.Text      `json:"username"`
	AccessToken    string           `json:"access_token"`
	RefreshToken   string           `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamp `json:"token_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.StravaUserID,
		arg.Username,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.Username,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, strava_user_id, username, access_token, refresh_token, token_expires_at, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.Username,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByStravaID = `-- name: GetUserByStravaID :one
SELECT id, strava_user_id, username, access_token, refresh_token, token_expires_at, created_at, updated_at FROM users
WHERE strava_user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByStravaID(ctx context.Context, stravaUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStravaID, stravaUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.Username,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, strava_user_id, username, access_token, refresh_token, token_expires_at, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.StravaUserID,
			&i.Username,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserTokens = `-- name: UpdateUserTokens :one
UPDATE users
SET access_token = $2,
    refresh_token = $3,
    token_expires_at = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, strava_user_id, username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type UpdateUserTokensParams struct {
	ID             int32            `json:"id"`
	AccessToken    string           `json:"access_token"`
	RefreshToken   string           `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamp `json:"token_expires_at"`
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.Username,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    strava_user_id,
    username,
    access_token,
    refresh_token,
    token_expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (strava_user_id)
DO UPDATE SET
    username = EXCLUDED.username,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    token_expires_at = EXCLUDED.token_expires_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, strava_user_id, username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type UpsertUserParams struct {
	StravaUserID   int64            `json:"strava_user_id"`
	Username       pgtype.Text      `json:"username"`
	AccessToken    string           `json:"access_token"`
	RefreshToken   string           `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamp `json:"token_expires_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.StravaUserID,
		arg.Username,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.Username,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
